### ISSUE TITLE
Signal to update field on Video model after conversion finished?

### ISSUE THREAD

**Issue by kvnramirez** [escaped/django-video-encoding#12]
Hi, I was wondering if it's possible to know if a conversion already finished to update a model? Maybe with a post_signal or something like that.

I want to update a field on the Model where I put the VideoField, e.g, I add a boolean field on the model where I put the VideoField, and when the conversion finished, I want to change that boolean value.

**Comment by escaped** [comment]
Hey,

yeah... Sounds like a reasonable request :) I guess having signals for the following events would be useful:

- whenever one conversion for a given video is completed
- whenever all conversions for a given video are completed

**Comment by derek-adair** [comment]
Thanks for your hard work, great code.

I am getting a recursion error when I implement the solution to update `processed = True` as implemented in the [README](https://github.com/escaped/django-video-encoding#signals).  Currently my plan is to detect if the file has changed before I call convert_all_videos.
