### ISSUE TITLE
Make sure it works with django-storages...

### ISSUE THREAD

**Issue by bashu** [escaped/django-video-encoding#13]
...especially with AWS S3

**Comment by lifenautjoe** [comment]
What is the status of this?

**Comment by bashu** [comment]
@lifenautjoe I will answer raised questions by @escaped and update this PR. Right now I am too busy...

**Comment by lifenautjoe** [comment]
You are absolutely right on this one @bashu .

The library indeed does not work with django storages.

**Comment by lifenautjoe** [comment]
The PR https://github.com/escaped/django-video-encoding/pull/19 fixes this, also processing :-)
