### ISSUE TITLE
Video compression 

### ISSUE THREAD

**Issue by albertpawlowski** [escaped/django-video-encoding#32]
Hi! Do you think it's possible to use this library for video compression purposes? I managed to run a celery script responsible for compressing videos using FFmpeg in my project. It works fine, but it looks like you guys covered many other aspects that I possibly didn't think of in my solution (like storages and S3). I wondered how I could accomplish a similar thing but using your library instead (maybe with some tweaks). Is it something that is already covered or needs to be implemented yet?

**Comment by escaped** [comment]
Hey :)

based on your description, I would say, that this library covers all the requirements you have.
* use FFmpeg for encoding
* run compression/encoding in a celery/rq/... worker
* store data to S3

The compression is [pre-defined](https://github.com/escaped/django-video-encoding/blob/977145d0fd80f72b43c9b8b469f7abc262409bfa/video_encoding/config.py#L11) for FFmpeg, but it is easy to override the config depending on your needs - the current configuration is optimized for the web. An alternative/more modern configuration can be found here: https://github.com/escaped/django-video-encoding/issues/9

I would suggest you have another look at the README and/or play around with the [example project](https://github.com/escaped/django-video-encoding/tree/master/test_proj).

**Comment by albertpawlowski** [comment]
Thank you for your advice. I ended up staying with my own script but got a lot of insights from your code on how to work with storages and files. I was finally able to make it work with S3 and save compressed files there. 

If I would ever go about doing something similar in the future I would definitely go with your library.

**Comment by escaped** [comment]
Thank you. I am glad that it was helpful. :)
